// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package utils;

public final class ServiceImpl_Stub
    extends java.rmi.server.RemoteStub
    implements utils.Service
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_farenheitToCelsious_0;
    private static java.lang.reflect.Method $method_getDate_1;
    
    static {
	try {
	    $method_farenheitToCelsious_0 = utils.Service.class.getMethod("farenheitToCelsious", new java.lang.Class[] {double.class});
	    $method_getDate_1 = utils.Service.class.getMethod("getDate", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ServiceImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of farenheitToCelsious(double)
    public double farenheitToCelsious(double $param_double_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_farenheitToCelsious_0, new java.lang.Object[] {new java.lang.Double($param_double_1)}, 1028507186200687892L);
	    return ((java.lang.Double) $result).doubleValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getDate()
    public java.util.Date getDate()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDate_1, null, -1017285815713287420L);
	    return ((java.util.Date) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
